---
name: Sys-Filesystem
version: 1.23
author:
  - 'Nicola Worthington <nicolaw@cpan.org>'
abstract: Retrieve list of filesystems and their properties
license: open_source
requires:
  Carp: 0
  FileHandle: 0
recommends:
  Test: 0
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
provides:
  Sys::Filesystem:
    file: lib/Sys/Filesystem.pm
    version: 1.23
  Sys::Filesystem::Aix:
    file: lib/Sys/Filesystem/Aix.pm
    version: 1.05
  Sys::Filesystem::Cygwin:
    file: lib/Sys/Filesystem/Cygwin.pm
    version: 1.07
  Sys::Filesystem::Darwin:
    file: lib/Sys/Filesystem/Darwin.pm
    version: 0.22
  Sys::Filesystem::Dummy:
    file: lib/Sys/Filesystem/Dummy.pm
    version: 1.06
  Sys::Filesystem::Freebsd:
    file: lib/Sys/Filesystem/Freebsd.pm
    version: 1.05
  Sys::Filesystem::Linux:
    file: lib/Sys/Filesystem/Linux.pm
    version: 1.13
  Sys::Filesystem::Mswin32:
    file: lib/Sys/Filesystem/Mswin32.pm
    version: 1.05
  Sys::Filesystem::Solaris:
    file: lib/Sys/Filesystem/Solaris.pm
    version: 1.13
  Sys::Filesystem::Unix:
    file: lib/Sys/Filesystem/Unix.pm
    version: 1.05
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
