---
abstract: 'Retrieve list of filesystems and their properties'
author:
  - 'Jens Rehsack <rehsack@cpan.org>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sys-Filesystem
provides:
  Sys::Filesystem:
    file: lib/Sys/Filesystem.pm
    version: 1.28
  Sys::Filesystem::Aix:
    file: lib/Sys/Filesystem/Aix.pm
    version: 1.28
  Sys::Filesystem::Cygwin:
    file: lib/Sys/Filesystem/Cygwin.pm
    version: 1.28
  Sys::Filesystem::Darwin:
    file: lib/Sys/Filesystem/Darwin.pm
    version: 1.28
  Sys::Filesystem::Dummy:
    file: lib/Sys/Filesystem/Dummy.pm
    version: 1.28
  Sys::Filesystem::Freebsd:
    file: lib/Sys/Filesystem/Freebsd.pm
    version: 1.28
  Sys::Filesystem::Hpux:
    file: lib/Sys/Filesystem/Hpux.pm
    version: 1.28
  Sys::Filesystem::Linux:
    file: lib/Sys/Filesystem/Linux.pm
    version: 1.28
  Sys::Filesystem::Mswin32:
    file: lib/Sys/Filesystem/Mswin32.pm
    version: 1.28
  Sys::Filesystem::Netbsd:
    file: lib/Sys/Filesystem/Netbsd.pm
    version: 1.28
  Sys::Filesystem::Solaris:
    file: lib/Sys/Filesystem/Solaris.pm
    version: 1.28
  Sys::Filesystem::Unix:
    file: lib/Sys/Filesystem/Unix.pm
    version: 1.28
recommends:
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
requires:
  Carp: 0
  FindBin: 0
  IO: 0
  Module::Pluggable: 3.9
  Params::Util: 1.00
  perl: 5.006
resources:
  license: http://www.apache.org/licenses/LICENSE-2.0.txt
version: 1.28
